// frontend/src/components/YouTubeAnalytics.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { motion } from 'framer-motion';
import { toast } from 'react-hot-toast';
import KeywordAnalyzer from './KeywordAnalyzer';
import ThumbnailAnalyzer from './ThumbnailAnalyzer';
import ChannelComparison from './ChannelComparison';
import VideoDownloader from './VideoDownloader';

const YouTubeAnalytics = () => {
  // États
  const [trends, setTrends] = useState([]);
  const [videoId, setVideoId] = useState('');
  const [channelId, setChannelId] = useState('');
  const [category, setCategory] = useState('general');
  const [videoAnalysis, setVideoAnalysis] = useState(null);
  const [channelAnalysis, setChannelAnalysis] = useState(null);
  const [suggestions, setSuggestions] = useState([]);
  const [loading, setLoading] = useState({
    trends: false,
    video: false,
    channel: false,
    suggestions: false
  });
  const [activeTab, setActiveTab] = useState('trends');

  const tabs = [
    { id: 'trends', label: 'Tendances' },
    { id: 'keywords', label: 'Mots-clés' },
    { id: 'thumbnails', label: 'Miniatures' },
    { id: 'comparison', label: 'Comparaison' },
    { id: 'download', label: 'Téléchargement' }
  ];

  // Gestionnaires d'événements
  const getTrends = async () => {
    setLoading(prev => ({ ...prev, trends: true }));
    try {
      const response = await axios.get('/api/youtube/trending');
      setTrends(response.data);
      toast.success('Tendances récupérées avec succès');
    } catch (error) {
      console.error('Erreur lors de la récupération des tendances:', error);
      toast.error('Erreur lors de la récupération des tendances');
    } finally {
      setLoading(prev => ({ ...prev, trends: false }));
    }
  };

  const analyzeVideo = async () => {
    if (!videoId) {
      toast.error('Veuillez entrer un ID de vidéo');
      return;
    }
    setLoading(prev => ({ ...prev, video: true }));
    try {
      const response = await axios.get(`/api/youtube/analyze/video/${videoId}`);
      setVideoAnalysis(response.data);
      toast.success('Analyse de la vidéo terminée');
    } catch (error) {
      console.error('Erreur lors de l\'analyse de la vidéo:', error);
      toast.error('Erreur lors de l\'analyse de la vidéo');
    } finally {
      setLoading(prev => ({ ...prev, video: false }));
    }
  };

  const analyzeChannel = async () => {
    if (!channelId) {
      toast.error('Veuillez entrer un ID de chaîne');
      return;
    }
    setLoading(prev => ({ ...prev, channel: true }));
    try {
      const response = await axios.get(`/api/youtube/analyze/channel/${channelId}`);
      setChannelAnalysis(response.data);
      toast.success('Analyse de la chaîne terminée');
    } catch (error) {
      console.error('Erreur lors de l\'analyse de la chaîne:', error);
      toast.error('Erreur lors de l\'analyse de la chaîne');
    } finally {
      setLoading(prev => ({ ...prev, channel: false }));
    }
  };

  const getSuggestions = async () => {
    setLoading(prev => ({ ...prev, suggestions: true }));
    try {
      const response = await axios.get(`/api/youtube/suggestions?category=${category}`);
      setSuggestions(response.data);
      toast.success('Suggestions générées avec succès');
    } catch (error) {
      console.error('Erreur lors de la récupération des suggestions:', error);
      toast.error('Erreur lors de la récupération des suggestions');
    } finally {
      setLoading(prev => ({ ...prev, suggestions: false }));
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <h2 className="text-3xl font-bold text-red-600 text-center mb-8">YouTube Analytics</h2>

      {/* Navigation */}
      <div className="mb-8">
        <nav className="flex space-x-4">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 rounded-md ${
                activeTab === tab.id
                  ? 'bg-red-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </nav>
      </div>

      {/* Contenu des onglets */}
      <motion.div
        key={activeTab}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -20 }}
        transition={{ duration: 0.2 }}
      >
        {activeTab === 'trends' && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Section Tendances */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-lg shadow-md p-6 mb-8"
            >
              <h3 className="text-xl font-semibold mb-4">Tendances YouTube</h3>
              <button
                onClick={getTrends}
                disabled={loading.trends}
                className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 disabled:bg-gray-400"
              >
                {loading.trends ? 'Chargement...' : 'Voir les tendances'}
              </button>

              {trends.length > 0 && (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
                  {trends.map((video) => (
                    <div key={video.id} className="border rounded-lg p-4">
                      <h4 className="font-medium">{video.title}</h4>
                      <p>Vues: {video.views}</p>
                      <p>Engagement: {video.engagementRate}%</p>
                    </div>
                  ))}
                </div>
              )}
            </motion.div>

            {/* Section Analyse de vidéo */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-lg shadow-md p-6 mb-8"
            >
              <h3 className="text-xl font-semibold mb-4">Analyser une vidéo</h3>
              <div className="flex gap-4">
                <input
                  type="text"
                  value={videoId}
                  onChange={(e) => setVideoId(e.target.value)}
                  placeholder="ID de la vidéo YouTube"
                  className="flex-1 border rounded-md px-3 py-2"
                />
                <button
                  onClick={analyzeVideo}
                  disabled={loading.video}
                  className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 disabled:bg-gray-400"
                >
                  {loading.video ? 'Analyse...' : 'Analyser'}
                </button>
              </div>

              {videoAnalysis && (
                <div className="mt-4 bg-gray-50 rounded-lg p-4">
                  <pre className="whitespace-pre-wrap">
                    {JSON.stringify(videoAnalysis, null, 2)}
                  </pre>
                </div>
              )}
            </motion.div>

            {/* Section Analyse de chaîne */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-lg shadow-md p-6 mb-8"
            >
              <h3 className="text-xl font-semibold mb-4">Analyser une chaîne</h3>
              <div className="flex gap-4">
                <input
                  type="text"
                  value={channelId}
                  onChange={(e) => setChannelId(e.target.value)}
                  placeholder="ID de la chaîne YouTube"
                  className="flex-1 border rounded-md px-3 py-2"
                />
                <button
                  onClick={analyzeChannel}
                  disabled={loading.channel}
                  className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 disabled:bg-gray-400"
                >
                  {loading.channel ? 'Analyse...' : 'Analyser'}
                </button>
              </div>

              {channelAnalysis && (
                <div className="mt-4 bg-gray-50 rounded-lg p-4">
                  <pre className="whitespace-pre-wrap">
                    {JSON.stringify(channelAnalysis, null, 2)}
                  </pre>
                </div>
              )}
            </motion.div>

            {/* Section Suggestions */}
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white rounded-lg shadow-md p-6"
            >
              <h3 className="text-xl font-semibold mb-4">Suggestions de contenu</h3>
              <div className="flex gap-4">
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="flex-1 border rounded-md px-3 py-2"
                >
                  <option value="general">Général</option>
                  <option value="gaming">Gaming</option>
                  <option value="education">Education</option>
                  <option value="entertainment">Divertissement</option>
                </select>
                <button
                  onClick={getSuggestions}
                  disabled={loading.suggestions}
                  className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 disabled:bg-gray-400"
                >
                  {loading.suggestions ? 'Génération...' : 'Obtenir des suggestions'}
                </button>
              </div>

              {suggestions.length > 0 && (
                <div className="mt-4 space-y-2">
                  {suggestions.map((suggestion, index) => (
                    <div key={index} className="bg-gray-50 rounded-lg p-4">
                      {suggestion}
                    </div>
                  ))}
                </div>
              )}
            </motion.div>
          </div>
        )}

        {activeTab === 'keywords' && <KeywordAnalyzer />}
        
        {activeTab === 'thumbnails' && <ThumbnailAnalyzer />}
        
        {activeTab === 'comparison' && <ChannelComparison />}
        
        {activeTab === 'download' && <VideoDownloader />}
      </motion.div>
    </div>
  );
};

export default YouTubeAnalytics;

// frontend/src/components/YouTubeAnalytics.vue
<template>
  <div class="youtube-analytics">
    <h2>YouTube Analytics</h2>
    
    <!-- Tendances -->
    <div class="section">
      <h3>Tendances YouTube</h3>
      <button @click="getTrends" :disabled="loadingTrends">
        {{ loadingTrends ? 'Chargement...' : 'Voir les tendances' }}
      </button>
      <div v-if="trends.length" class="trends-grid">
        <div v-for="video in trends" :key="video.id" class="trend-card">
          <h4>{{ video.title }}</h4>
          <p>Vues: {{ video.views }}</p>
          <p>Engagement: {{ video.engagementRate }}%</p>
        </div>
      </div>
    </div>

    <!-- Analyse de vidéo -->
    <div class="section">
      <h3>Analyser une vidéo</h3>
      <input v-model="videoId" placeholder="ID de la vidéo YouTube">
      <button @click="analyzeVideo" :disabled="loadingVideo">
        {{ loadingVideo ? 'Analyse...' : 'Analyser' }}
      </button>
      <div v-if="videoAnalysis" class="analysis-card">
        <h4>Résultats de l'analyse</h4>
        <pre>{{ JSON.stringify(videoAnalysis, null, 2) }}</pre>
      </div>
    </div>

    <!-- Analyse de chaîne -->
    <div class="section">
      <h3>Analyser une chaîne</h3>
      <input v-model="channelId" placeholder="ID de la chaîne YouTube">
      <button @click="analyzeChannel" :disabled="loadingChannel">
        {{ loadingChannel ? 'Analyse...' : 'Analyser' }}
      </button>
      <div v-if="channelAnalysis" class="analysis-card">
        <h4>Analyse de la chaîne</h4>
        <pre>{{ JSON.stringify(channelAnalysis, null, 2) }}</pre>
      </div>
    </div>

    <!-- Suggestions de contenu -->
    <div class="section">
      <h3>Suggestions de contenu</h3>
      <select v-model="category">
        <option value="general">Général</option>
        <option value="gaming">Gaming</option>
        <option value="education">Education</option>
        <option value="entertainment">Divertissement</option>
      </select>
      <button @click="getSuggestions" :disabled="loadingSuggestions">
        {{ loadingSuggestions ? 'Génération...' : 'Obtenir des suggestions' }}
      </button>
      <div v-if="suggestions.length" class="suggestions-list">
        <div v-for="(suggestion, index) in suggestions" :key="index" class="suggestion-card">
          <p>{{ suggestion }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'YouTubeAnalytics',
  data() {
    return {
      trends: [],
      videoId: '',
      channelId: '',
      category: 'general',
      videoAnalysis: null,
      channelAnalysis: null,
      suggestions: [],
      loadingTrends: false,
      loadingVideo: false,
      loadingChannel: false,
      loadingSuggestions: false
    }
  },
  methods: {
    async getTrends() {
      this.loadingTrends = true;
      try {
        const response = await axios.get('/api/youtube/trending');
        this.trends = response.data;
      } catch (error) {
        console.error('Erreur lors de la récupération des tendances:', error);
      } finally {
        this.loadingTrends = false;
      }
    },
    async analyzeVideo() {
      if (!this.videoId) return;
      this.loadingVideo = true;
      try {
        const response = await axios.get(`/api/youtube/analyze/video/${this.videoId}`);
        this.videoAnalysis = response.data;
      } catch (error) {
        console.error('Erreur lors de l\'analyse de la vidéo:', error);
      } finally {
        this.loadingVideo = false;
      }
    },
    async analyzeChannel() {
      if (!this.channelId) return;
      this.loadingChannel = true;
      try {
        const response = await axios.get(`/api/youtube/analyze/channel/${this.channelId}`);
        this.channelAnalysis = response.data;
      } catch (error) {
        console.error('Erreur lors de l\'analyse de la chaîne:', error);
      } finally {
        this.loadingChannel = false;
      }
    },
    async getSuggestions() {
      this.loadingSuggestions = true;
      try {
        const response = await axios.get(`/api/youtube/suggestions?category=${this.category}`);
        this.suggestions = response.data;
      } catch (error) {
        console.error('Erreur lors de la récupération des suggestions:', error);
      } finally {
        this.loadingSuggestions = false;
      }
    }
  }
}
</script>

<style scoped>
.youtube-analytics {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
}

.section {
  margin-bottom: 30px;
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

h2 {
  color: #ff0000;
  text-align: center;
  margin-bottom: 30px;
}

h3 {
  color: #333;
  margin-bottom: 15px;
}

.trends-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 20px;
  margin-top: 20px;
}

.trend-card {
  padding: 15px;
  background: #f8f9fa;
  border-radius: 6px;
  border: 1px solid #dee2e6;
}

.analysis-card {
  margin-top: 20px;
  padding: 15px;
  background: #f8f9fa;
  border-radius: 6px;
  overflow-x: auto;
}

.suggestions-list {
  margin-top: 20px;
}

.suggestion-card {
  padding: 10px;
  margin-bottom: 10px;
  background: #f8f9fa;
  border-radius: 4px;
}

button {
  background: #ff0000;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-right: 10px;
}

button:disabled {
  background: #ccc;
  cursor: not-allowed;
}

input, select {
  padding: 8px;
  margin-right: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  width: 200px;
}

pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}
</style>
